### ISSUE TITLE
Login for IBMers

### ISSUE THREAD

**Issue by RobertJBarron** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#10]
When you run bx -login, if you are an IBMer then you need either the API or the SSO method.
Our install_bluemix.sh script doesn't support the SSO method.
Not everyone knows how to get an API key - I think that should be documented too.

**Comment by gangchen03** [comment]
For federated users, we need to address the SSO login type by passing the API key

**Comment by fabiogomezdiaz** [comment]
Fixed by 4f8ed67. Updated the README to make creating an API mandatory to use the scripts
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#create-a-bluemix-api-key.

Please reopen if having same issues
