### ISSUE TITLE
Install  script doesn't support Spaces with a " " in the middle as a parameter

### ISSUE THREAD

**Issue by RobertJBarron** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#11]
Install script doesn't support Spaces with a " " in the middle as a parameter

**Comment by fabiogomezdiaz** [comment]
@RobertJBarron what are you trying to do? Given some other issues with optional parameters, we are going to make all parameters required to address all login scenarios, including #10 #12 and #15. And we are also going to provide necessary docs to obtain everything that's required.

**Comment by RobertJBarron** [comment]
I tried to deploy BC to a space called "Service Management"

**Comment by fabiogomezdiaz** [comment]
@RobertJBarron closing this for now as our installation instructions have dramatically changed since.

If having new problems, please open a new issue.
