### ISSUE TITLE
helm repo URL of bluecompute spring needs to be updated

### ISSUE THREAD

**Issue by naoto30** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#110]
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/spring/README.md

The URL of helm repository in this README is 404.
 https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce

**Comment by naoto30** [comment]
correct one as helm repo URL is:
https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce

(from browser)
https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/index.yaml

**Comment by osowski** [comment]
Fixed via https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/pull/111
