### ISSUE TITLE
Login for federated ID requires an API Key for subsequent commands to work.

### ISSUE THREAD

**Issue by DevOps-GM** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#12]
When you log in to bluemix as a federated user, you need to use the option to specify the API key so that subsequent commands work.  To do this a person needs to log in using the SSO option and then issue the command to get the API key for use in subsequent commands.  This needs to be updated in the readme file.

**Comment by fabiogomezdiaz** [comment]
Fixed by 4f8ed67. Updated the README to make creating an API mandatory to use the scripts
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#create-a-bluemix-api-key.

Please reopen if having same issues
