### ISSUE TITLE
Formatting issue in MicroProfile Chart documentation

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#129]
Towards the end of https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile/bluecompute-mp#zipkin, there is a misplaced backtick that breaks the formatting for the rest of the page.  

This should be a simple fix, but wanted to note it for documentation review.

**Comment by Hemankita** [comment]
Corrected it in the below pull request. Please have a look.

https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/pull/136

**Comment by Hemankita** [comment]
Changes merged
