### ISSUE TITLE
Script for accessing the Kubernetes dashboard

### ISSUE THREAD

**Issue by DevOps-GM** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#13]
There are many steps that need to be performed in order to access the Kubernetes dashboard.  A script should be provided to make this easy for the end user.

**Comment by fabiogomezdiaz** [comment]
@DevOps-GM for such instructions, please reference the IBM Cloud Container Service documentation below:
https://console.bluemix.net/docs/containers/cs_app.html#cli_dashboard

Closing this issue as providing such scripts is beyond the scope of this project.
