### ISSUE TITLE
Copy over PodSecurityPolicy from `spring` branch

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#133]
The Elasticsearch containers still require the elevated privileges, so we should copy over the `PodSecurityPolicy` files from the `spring` branch and include them in the documentation.

This is very relevant when deploying to a non-`default` namespace, which is often preferred and recommended.

**Comment by Hemankita** [comment]
Copied the files over to `/docs/pod-security-policy`
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/pull/136

Should I mention about this anywhere in the main README.md?

**Comment by fabiogomezdiaz** [comment]
@osowski @Hemankita no need to copy this over. I actually forgot to delete it after I moved it. I made the chart automatically elevate privileges if installed in a non-default folder. I did it with these files:
- https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/spring/bluecompute-ce/templates/pod_security_policy.yaml
- https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/spring/bluecompute-ce/templates/cluster_role.yaml
- https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/spring/bluecompute-ce/templates/cluster_role_binding.yaml

The first line in each of these checks whether installing in non-`default` namespace.

**Comment by Hemankita** [comment]
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/pull/137

Modified the charts to automatically elevate privileges if installed in a non-default folder just like Fabio mentioned. Also, modified the keystore secret generation to work correctly in non-default namespace.

**Comment by osowski** [comment]
Closing via https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/commit/43aaa2a4ca23c50c13096dde375884dbb9af75c8
