### ISSUE TITLE
Customer create user job has errors

### ISSUE THREAD

**Issue by JustinKuli** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#156]
Our deployment of the `0.0.8` version seems to have succeeded, but the `customer-create-user` job needed to be attempted twice before it was done. In the logs of both pods (the one with Error status, and the one with Completed status) we found this:
```Customer with name user already existsCustomer with name user already exists```
over and over.

I'm curious if this indicates a problem in our deployment specifically, or if this is "normal." If it is normal, is there anything we can do to address the root cause?

**Comment by phemankita** [comment]
No longer valid
