### ISSUE TITLE
When installing using the script, the install froze on the last step and did not complete.

### ISSUE THREAD

**Issue by DevOps-GM** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#17]
We should ensure that the install will run through to completion every time it runs.  Not sure what caused the failure, but it required a delete and reinstall to get the application installed successfully.

**Comment by fabiogomezdiaz** [comment]
@DevOps-GM this should have been taken care of. It took place when installing the web application.  Please reopen if you see the same issue
