### ISSUE TITLE
install_cli fails

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#18]
root@linux:~/refarch-cloudnative-kubernetes# ./install_cli.sh

Installing Bluemix CLI (bx)...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.5M  100 12.5M    0     0  5010k      0  0:00:02  0:00:02 --:--:-- 5009k
tar (child): Bluemix_CLI.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
./install_cli.sh: line 19: Bluemix_CLI/install_bluemix_cli: No such file or directory

**Comment by fabiogomezdiaz** [comment]
Fixed by e32f38f. Closing for now. Please reopen if getting the same issue. Else, open a new issue.
