### ISSUE TITLE
Use Official Elasticsearch Chart instead of Helm Community

### ISSUE THREAD

**Issue by fabiogomezdiaz** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#203]
The official char has smaller memory footprint.

The goal is that the we can deploy bluecompute in the free IKS cluster.

**Comment by phemankita** [comment]
We are currently using a version of bluecompute to deploy it on free IKS cluster.

https://github.com/ibm-cloud-architecture/light-bluecompute

This is currently being used in the tutorial as well
