### ISSUE TITLE
Failure to create ImagePolicy in an ICP 3.2.0 cluster

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#205]
I have an ICP 3.2.0 CE version and I am following the instructions at

https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/microprofile/docs/icp.md

When I run the command 
``
kubectl apply -f https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/microprofile/static/image_policy.yaml
``

I get the following error:

``
Eduardos-MacBook-Air:terraform-ibm-openshift edu$ kubectl apply -f https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/microprofile/static/image_policy.yaml
error: unable to recognize "https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/microprofile/static/image_policy.yaml": no matches for kind "ImagePolicy" in version "securityenforcement.admission.cloud.ibm.com/v1beta1"
``

**Comment by patrocinio** [comment]
It seems the Image Security Enforcement is not enabled in my cluster, so the CR creation failed.

See documentation at

https://www.ibm.com/support/knowledgecenter/SSBS6K_3.2.0/manage_images/image_security.html

It will be good to document that this step is necessary only when Image Security is enforced.

**Comment by yeekangc** [comment]
@dshimo @jjvilleg, can one of you take a look at this?  Thank you.

**Comment by phemankita** [comment]
Not supporting ICP any more
