### ISSUE TITLE
Upgrade apiVersion in YAMLs

### ISSUE THREAD

**Issue by kevinwlau** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#210]
Kubernetes 1.16.0 removes support for some deprecated APIs: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Will need to update many of our YAML files to use the new APIs to replace the deprecated ones.

Edit: Additionally, it seems that Deployments now need a `spec.selector.matchLabel` field.

**Comment by evie-lau** [comment]
- [x] web - https://github.com/ibm-cloud-architecture/refarch-cloudnative-bluecompute-web/pull/89 passed
- [x] orders - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/pull/92 passed
- [x] inventory - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/pull/118
- [x] catalog - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-catalog/pull/35
- [x] auth - https://github.com/ibm-cloud-architecture/refarch-cloudnative-auth/pull/1 - passed
- [x] customer - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/pull/97 waiting on couchdb helm chart to be updated

- [x] main repo - https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/pull/208, https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/pull/216

**Comment by evie-lau** [comment]
#216 released bluecompute 0.1.2, which finalized the changes to work with kube 1.16, along with all the proper project dependencies.
