### ISSUE TITLE
Wrong MYSQL_HOST env in order deployment 

### ISSUE THREAD

**Issue by aarenw** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#212]
The host in deployment is orders-mariadb-orders-mariadb, but he mariadb service name is bluecompute-orders-mariadb. 
There are two workaround :
1, change orders-mariadb-orders-mariadb to bluecompute-orders-mariadb the deployment yaml file;
2, another way is create new service orders-mariadb-orders-mariadb, the content same as bluecompute-orders-mariadb.

**Comment by doormat18** [comment]
For number 2 suggested workaround by @aarenw define another mariadb instance using the following command (helm v2):

$ helm upgrade --install orders-mariadb \
   --version 5.2.2 \
   --set nameOverride=orders-mariadb \
   --set service.port=3307 \
   --set rootUser.password=admin123 \
   --set db.user=dbuser \
   --set db.password=password \
   --set db.name=ordersdb \
   --set replication.enabled=false \
   --set master.persistence.enabled=false \
   --set slave.replicas=1 \
   --set slave.persistence.enabled=false \
   stable/mariadb

The orders pod should then initialize.

**Comment by doormat18** [comment]
This issue is now fixed in chart v0.0.10 of the bluecompute-ce app spring deployment
