### ISSUE TITLE
jq should be added to the list of requirements

### ISSUE THREAD

**Issue by xavierloup** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#22]
In Readme.md, "jq" should should be added to the list of requirements.
This program is used by install_bluecompute_ce.sh

**Comment by fabiogomezdiaz** [comment]
@xavierloup we have since changed the installation instructions. Here is a link:
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#deploy-to-kubernetes-cluster

Closing for now. If you have any other problems, please open a new issue.
