### ISSUE TITLE
Support BlueCompute deployment to OpenShift 4.x

### ISSUE THREAD

**Issue by gangchen03** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#221]
Sunset the support for IBM Cloud Private (ICP).

We need to validate and test the deployment on:

- IBM Cloud ROKS (Managed OpenShift)
- Generic OpenShift cluster

Update the instruction/guide on:
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/spring#deploy-the-application

**Comment by gangchen03** [comment]
Specifically the section https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/spring#deploy-bluecompute-to-ibm-cloud-private
ICP is no longer valid option.
Deploy to OpenShift 4.3

**Comment by phemankita** [comment]
Updated the instructions 

https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/spring#create-a-openshift-cluster
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/spring#deploy-to-openshift-cluster
