### ISSUE TITLE
deploy CE edition to a kubernetes namespace

### ISSUE THREAD

**Issue by jkwong888** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#23]
allow users to be able to deploy CE stack to different namespaces, in cases where the users share a large cluster

**Comment by fabiogomezdiaz** [comment]
@jkwong888 closing this as this ability already exists. Leaving a link to the asset you created for others' sake.

https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/master/PodSecurityPolicy/PodSecurityPolicy.md
