### ISSUE TITLE
install_cli.bat expects curl to be installed 

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#27]

**Comment by RobertJBarron** [comment]
Hi @patrocinio 
It's a bootstrap recursion issue - I need cURL to install all the other tools and I can't depend on it to already exist on the user's computer.

Therefore, it is part of the repository and should be automatically downloaded when you clone the repository. Did this not work for you?
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/kube-int/win_utils

**Comment by patrocinio** [comment]
@RobertJBarron I was running on PowerShell, and the script didn't pick up the PATH. 
We may need to test with PowerShell.
