### ISSUE TITLE
User Creation failed with invalid_token error

### ISSUE THREAD

**Issue by mossuchida** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#3]
I am trying to create a user in my BlueCompute deployed in my cluster, but it gives me error: invalid_token

curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <JWT>" -d '{"username": "foo", "password": "bar", "firstName": "foo", "lastName": "bar", "email": "foo@bar.com"}' -i http://127.0.0.1:8080/micro/customer
HTTP/1.1 401 Unauthorized
Date: Thu, 11 May 2017 21:33:21 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Cache-Control: no-store
Pragma: no-cache
WWW-Authenticate: Bearer realm="oauth2-resource", error="invalid_token", error_description="Cannot convert access token to JSON"
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Server: Jetty(9.2.13.v20150730)

Steps to generate Token:
- Run following code to generate Key: kubectl get secrets hs256-key -o yaml
- Use this key in https://jwt.io/ as "Secret" (secret base64 encoded unchecked), using the following for Payload for H256 algorithm, generate encoding to use as a bearer token = <JWT>:
{
  "scope": [ "blue" ],
  "user_name": "admin"
}

Port forwarding from my local VM to Armada Cluster deployed in Bluemix:
- Get Customer pod name : kubectl get pods
- Get Port Number for the pod : kubectl get pods bluecompute-customer-2411758560-9s7vj --template='{{(index (index .spec.containers 0).ports 0).containerPort}}{{"\n"}}'
- Forward port : kubectl port-forward bluecompute-customer-2411758560-9s7vj 8080:8080

**Comment by jkwong888** [comment]
you are missing the token in the header:

curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer "

I am working on adding user creation as a post install hook in the helm chart,so this should be fixed there.

**Comment by mossuchida** [comment]
Oops, wrong one to paste, here is the issue that I am hitting now:
[root@enos ~]# curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer bGhhbUZSempBbFFTVUo4UTY3Z0ROejd0STNGZkFHb0JMbTFTZHltdThqYmdpS0h2aVdzWm1paUVKd05ITGYzV2lSMkYwcFYzYjBjdDZ5NW1pQ3ByOXRlWWlZRnFSQnZmRnhXRTdLOEdVZFZyb2JiSHlsc0QzUnJ2ZVRtMDVIT0M4R3pkYW1WeTJrVU1uS2ZUM1JlWUhnWk9WNzlLMHJPempLTU1CS1pTYkg4N1RFdklkaDlCc0htVUVHWnFoQVJQRnhUcWdDelo5dDJWRHdqN3RXaHRMOGZ0NlpKcGVUMzFwa21KemJDMk5JejZrQW9rMHZFclF0QzJ3R0Z4REs1Ug==" -d '{"username": "foo", "password": "bar", "firstName": "foo", "lastName": "bar", "email": "foo@bar.com"}' -i http://127.0.0.1:8080/micro/customer
HTTP/1.1 401 Unauthorized
Date: Fri, 12 May 2017 16:38:36 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Cache-Control: no-store
Pragma: no-cache
WWW-Authenticate: Bearer realm="oauth2-resource", error="invalid_token", error_description="Cannot convert access token to JSON"
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Server: Jetty(9.2.13.v20150730)

{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}

**Comment by mossuchida** [comment]
Oops, wrong one tho paste:
[root@enos ~]# curl -X POST -H "Content-Type: application/json" -H "Authorizan: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJibHVlIl0sInVzZXJfbmFtZSI6ImFkbWluIn0.zwvPjkJUQ2A5oI5y1340Op5C_GGSnBUojAEWELoQVl4" -d '{"username": "foo", "password": "bar", "firstName": "foo", "lastName": "bar", "email": "foo@bar.com"}' -i http://127.0.0.1:8080/micro/customer
HTTP/1.1 401 Unauthorized
Date: Fri, 12 May 2017 16:41:24 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Cache-Control: no-store
Pragma: no-cache
WWW-Authenticate: Bearer realm="oauth2-resource", error="invalid_token", error_description="Cannot convert access token to JSON"
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Server: Jetty(9.2.13.v20150730)

{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}
