### ISSUE TITLE
Add step to change password from `passw0rd`

### ISSUE THREAD

**Issue by josiemessa** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#31]
If this service is being deployed to a public endpoint please recommend that users change the password to something more secure in the instructions before deploying their web application so that they are not hacked (this happens all the time in Bluemix already)

**Comment by fabiogomezdiaz** [comment]
@josiemessa thanks for your valuable feedback. But adding a step to change the password is beyond the scope of this project.

Closing for now.

**Comment by pavittr** [comment]
@fabiogomezdiaz is there another repo that would have this in scope? Security advice to avoid hacks seems like a useful enough idea that we should probably include this step somewhere.

**Comment by jkwong888** [comment]
you should be able to modify the cloudant database directly, i believe the password is even stored in plaintext.  you can also add additional users if you like.  

please note that our application is not meant to be a production application, just a reference application to demonstrate an example microservices implementation on kubernetes.  you're welcome to provide input on what you think is a best practice for security, and we can incorporate it :)
