### ISSUE TITLE
Stock number is not updating after placing order

### ISSUE THREAD

**Issue by mossuchida** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#5]
When I place order, the stock number is not going down.
FYI, URL to check stock number : http://mosscluster.us-south.containers.mybluemix.net/catalog/13405

**Comment by mossuchida** [comment]
FYI, this is what I run from jmeter
![image](https://cloud.githubusercontent.com/assets/12548207/26163817/c5c212a8-3af8-11e7-9a91-ebb990ebf26a.png)

**Comment by mossuchida** [comment]
This is what I get
![image](https://cloud.githubusercontent.com/assets/12548207/26163842/d82ebcc0-3af8-11e7-8536-f62f7a45e881.png)

**Comment by gangchen03** [comment]
no longer valid. closing the issue.
