### ISSUE TITLE
Provide updated instructions for installing bluecompute-ce on IBM Cloud Private V2.1

### ISSUE THREAD

**Issue by pdfruth** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#53]
There are instructions in the dev branch of [ibm-cloud-architecture/refarch-cloudnative-kubernetes](https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/dev#deploy-bluecompute-to-ibm-cloud-private-using-the-app-center) describing the steps to install bluecompute-ce into IBM Cloud Private (here https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/dev#deploy-bluecompute-to-ibm-cloud-private-using-the-app-center).
Attempts to install bluecompute-ce in IBM Cloud Private V2.1 CE do not work.  The following error message is seen in the ICP administrative console upon trying to install the bluecompute-ce helm chart from the Catalog;

`Internal service error : render error in “bluecompute-ce/charts/orders/charts/ibmcase-bluemix-service/templates/unbind_bluemix_service.yaml”: template: bluecompute-ce/charts/orders/charts/ibmcase-bluemix-service/templates/unbind_bluemix_service.yaml:4:82: executing “bluecompute-ce/charts/orders/charts/ibmcase-bluemix-service/templates/unbind_bluemix_service.yaml” at : wrong number of args for lower: want 1 got 0`

**Comment by jkwong888** [comment]
this is an open issue we logged with the ICP development team on their helm chart api.  in the meantime, you can follow the instructions to go back to installing using the helm cli.  we will update the instructions soon.
