### ISSUE TITLE
helm repo add ibmcase error

### ISSUE THREAD

**Issue by mikemoreira** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#55]
Hi, I tried to add this repo to helm following instructions from https://www.ibm.com/cloud/garage/tutorials/cloudnative-microservices-cloud-private, but the command : helm repo add ibmcase https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/master/docs/charts
Is returning this error : 
Error: Looks like "https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/master/docs/charts" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 312: mapping values are not allowed in this context
C:\>helm  version
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}

**Comment by fabiogomezdiaz** [comment]
@mikemoreira we have changed the repo URL. The updated instructions can be found here:
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#deploy-to-kubernetes-cluster

Closing this issue for now. Please reopen if you are still having issues.
