### ISSUE TITLE
Grafana Dashboards do not work on ICP 2.1

### ISSUE THREAD

**Issue by jxadro** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#58]
Hi.

I could deploy bluecompute application on ICP 2.1 using the ICP Catalogue UI, it throws an error but I think it was due to some timeout because I'm able to access and use the app without persistance enabled.

The problem is that if I try to import any grafana dashboards in the ICP out of the box Grafana the dashboard is shown empty. I have tried improting the file and copy&paste of the dashboard json file.

**Comment by RayStoner** [comment]
Hello Javier, I am closing this issue due to age. If you are still have issues with importing Dashboards please contact me directly.
