### ISSUE TITLE
unable to install bluecompute-ce and complete tutorial

### ISSUE THREAD

**Issue by nmiah2** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#69]
Im trying to follow task 4 in the following tutorial to deploy an app in the kubernetes cluster:
https://www.ibm.com/cloud/garage/tutorials/microservices-app-on-kubernetes?task=4

So I add the repository pointing to the url as indicated in the tutorial:
>helm repo add ibmcase https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts

Its added ok:
"ibmcase" has been added to your repositories

Then when I try the following instructions to install:
helm install --name bluecompute ibmcase/bluecompute-ce

I get error:
Error: failed to download "ibmcase/bluecompute-ce"

Does anyone have thoughts what might be wrong here ? 
I am running from windows cmd prompt.  Help appreciated.

**Comment by jkwong888** [comment]
The path to bluecompute-ce is:

https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce

(note the `bluecompute-ce` at the end of the path)

**Comment by fabiogomezdiaz** [comment]
Hi @nmiah2, thanks for pointing this out. Will have someone correct that link. Let us know if @jkwong888's suggestion works out for you

**Comment by nmiah2** [comment]
thanks @jkwong888  that definitely worked ! appreciated.
Hi @fabiogomezdiaz  yes you need to correct that path in the tutorial as @jkwong888 indicated. Otherwise might get people giving up on continuing the tutorial. 

Thanks guys !

**Comment by kimmytaft** [comment]
Link updated
