### ISSUE TITLE
What are the prerequirements to deploy the reference 'bluecompute-ce' application in a greenfield environment?

### ISSUE THREAD

**Issue by upenr** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#76]
This is not the demo environment. In my own private deployment, what are the prerequisites, related to PVs, PVCs, network, RAM, CPU etc before I deploy. Please clarify. 
Also, how does the deployment pick the right backend volume during deployment?
And finally, does the bluecompute-ce edition work with ppc64le? It's not mentioned on the Readme. Thanks.

**Comment by fabiogomezdiaz** [comment]
Hi @upenr,

**This is not the demo environment. In my own private deployment, what are the prerequisites, related to PVs, PVCs, network, RAM, CPU etc before I deploy. Please clarify.**
- We don't have specific requirements for CPU. As far as ram, we recommend at least 8GB as we point out [here](https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#create-a-kubernetes-cluster)
- By default, the chart does not use persistence (PVCs) by default. So, as long as you have the minimum RAM requirements, you should be able to deploy the chart.
- However, if you want persistence enabled and assuming you have a default storage class defined (NFS, GlusterFS, etc), you can enable persistence by changing [this](https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/master/bluecompute-ce/values.yaml#L7) parameter to `true`.
- If you want to specifically state which of your available storage classes to use, you can do so by specifying it in [this](https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/master/bluecompute-ce/values.yaml#L6) parameter.

**Also, how does the deployment pick the right backend volume during deployment?**
- Not sure if I understand your question, what do you mean by "pick the right backend"?

**And finally, does the bluecompute-ce edition work with ppc64le? It's not mentioned on the Readme.** 
- It does not at the moment. We do take PRs 🤓!

I hope this helps.

@jkwong888 anything you want to add?
