### ISSUE TITLE
Blue Compute on Open Liberty/MicroProfile in IBM Cloud Private with Microclimate

### ISSUE THREAD

**Issue by yeekangc** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#78]
- Re-base Blue Compute microservices to run on Open Liberty with MicroProfile technologies deploying to IBM Cloud Private using Microclimate
- Update and publish Architecture Center assets to show case this

**Comment by osowski** [comment]
Completed earlier this summer.  Blog series detailing work effort can be found at https://www.ibm.com/blogs/bluemix/2018/09/migrate-java-microservices-from-spring-to-microprofile-p1/.  

All BlueCompute repositories now have a `microprofile` branch to support this completed item.
