### ISSUE TITLE
install_cli.sh: brew: command not found

### ISSUE THREAD

**Issue by hbcafe** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#8]
Following the steps from the [readme](https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/master/README.md#step-1-environment-setup); script stops with prerequisite error for [Homebrew](https://brew.sh/) (?).

> Installing jq
> ./install_cli.sh: line 82: brew: command not found

If this is indeed a requirement, worth calling out in readme.

**Comment by gangchen03** [comment]
yeah, missed the step of adding homebrew to the script. Need to add into the install_cli.sh. On it.

**Comment by fabiogomezdiaz** [comment]
@hbcafe : **brew** is no longer required to install **jq** on Mac OS. Going to close this issue for now. Feel free to re-open this issue if you get the same issue. Else, feel free to open a new issue.
