### ISSUE TITLE
Installation on ICP 2.0.1 from Helm release fails.

### ISSUE THREAD

**Issue by vcailly** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#80]

**Comment by vcailly** [comment]
I have tried different versions of the helm release  with allways the same result. All deployements are starting properly except the bluecompute-ce-elasticsearch.   
if i execute a  kubectl describe deploy for this deployement i get  the following information with no more details :    ReplicaFailure True  FailedCreate

**Comment by jkwong888** [comment]
if you're installing on the non-default namespace, ICP default pod security policy will prevent elasticsearch from starting.  please follow the instructions in this document:

https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/master/PodSecurityPolicy/PodSecurityPolicy.md

**Comment by vcailly** [comment]
Thanks - I hae applied the instructions and now it is working properly.
