### ISSUE TITLE
Add "sources" field to all component charts

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#92]
Please add `sources:` lists to all the child component charts (pointing to the correlated `microprofile` branches of the individual repositories) so that they will show up in the index.yaml and we can associate tgz files with remote source code. 

See https://docs.helm.sh/developing_charts/#the-chart-yaml-file for reference.

**Comment by Hemankita** [comment]
Added the source and home labels to charts of all the child components.
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/pull/91
