### ISSUE TITLE
Issue getting bluecompute-ce to work with ICP2.1.0.2

### ISSUE THREAD

**Issue by rbhuet** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#95]
I'm just getting up to speed on ICP and followed the tutorial steps for installing bluecompute-ce using helm to a local ICP installation. 
https://www.ibm.com/cloud/garage/tutorials/cloudnative-microservices-cloud-private
However, none of the pods were successfully started.
![image](https://user-images.githubusercontent.com/17749422/43330588-3e1e2a4c-9189-11e8-857d-89200fd018d6.png)
How do I go about troubleshooting this helm release?  What is most likely to have gone wrong?
Any tips would be greatly appreciated.

**Comment by osowski** [comment]
@fabiogomezdiaz Can you take a look at this?

**Comment by phemankita** [comment]
Not supporting ICP any more
